version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    # shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: export-csv
    ports:
      - '5432:5432'

volumes:
  pgdata: {}
